title: Hong-ROK Lim
description: >-
  Interests in Productivity

baseurl: ""
url: "https://hongroklim.github.io"

# Theme
remote_theme: jekyll/minima@ffdb321
minima:
  skin: classic-dark # classic, dark, solarized-light, solarized-dark, solarized

# Author
author:
  name: "Hong Rok Lim"
  github: "hongroklim"
  email: "hongrr123@hanyang.ac.kr"

header_pages:
  # - "_pages/cv.md"
  - "_pages/tech.md"
  - "_pages/projects.md"
  # - "blog/index.html"

collections:
  projects:
    output: true

show_excerpts: true

paginate: 5
# paginate_path: "/blog/page:num"
paginate_path: "/page:num"

plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-feed

include:
  - _pages
  - _projects

sass:
  sass_dir: _sass
  style: compressed
